export const resumeData = {
  personal: {
    name: 'Kunal Mathur',
    phone: '+91 759-720-9058',
    email: 'mathurkunal000@gmail.com',
    linkedin: 'https://linkedin.com/in/kunal-mathur-612108267',
    github: 'https://github.com/kunal202426',
  },
  summary:
    'Full Stack Developer with production experience in scalable web apps, distributed systems, ML pipelines, and blockchain platforms. Proficient in React, Node.js, FastAPI, Python, and PostgreSQL.',
  education: [
    {
      school: 'Vellore Institute of Technology',
      degree: 'B.Tech in Computer Science & Engineering',
      specialization: 'Blockchain',
      period: '2022 - Present',
      location: 'Vellore, Tamil Nadu',
      url: 'https://vit.ac.in/',
    },
    {
      school: 'Turning Point School',
      degree: 'CBSE Class XII',
      period: '2020 - 2022',
      location: 'Ajmer, Rajasthan',
    },
    {
      school: 'Mayoor School',
      degree: 'CBSE Class X',
      period: '2018 - 2020',
      location: 'Ajmer, Rajasthan',
      url: 'https://mayoorschool.org/',
    },
  ],
  experience: [
    {
      company: 'YES Securities (YES Bank)',
      title: 'Full Stack Developer Intern',
      period: 'Jan 2026 - Jun 2026',
      location: 'Bengaluru, India',
      year: 2026,
      logo: '/yes-securities.png',
      achievements: [
        'Building production-grade features for OMNI trading platform using React, Node.js, and RESTful APIs in Agile sprints.',
        'Optimized backend microservices and PostgreSQL schema for improved reliability and reduced latency.',
      ],
    },
    {
      company: 'Team Levitate Hyperloop',
      title: 'Senior Engineer - AI & Software',
      period: '2024 - 2025',
      location: 'Vellore, India',
      year: 2024,
      logo: '/hyperloop-logo.png',
      achievements: [
        'Led development of levitatehyperloop.com - responsive 3D website with Three.js and React.',
        'Architected backend services and real-time data pipelines for pod hardware integration.',
      ],
    },
    {
      company: 'E-Cell VIT',
      title: 'Junior Core Member',
      period: '2023 - 2024',
      location: 'Vellore, India',
      year: 2023,
      logo: '/ecell-logo.png',
      achievements: [
        'Co-organized E-Summit and Futurepreneurs events with cross-functional planning.',
      ],
    },
  ],
  projects: [
    {
      title: 'Hybrid Stock Price Prediction System',
      subtitle: 'ML & Finance Tech',
      year: '2026',
      period: '2026',
      description: 'Hybrid ML ensemble with LSTM + LightGBM, FinBERT NLP sentiment analysis for real-time stock forecasting.',
      tags: ['Python', 'LSTM', 'LightGBM', 'NLP', 'React', 'Finance'],
      color: '#F5C542',
      featured: true,
      starred: true,
      category: 'ml',
      liveUrl: 'https://ysil.vercel.app/',
      githubUrl: 'https://github.com/kunal202426',
      achievements: [
        'Architected a hybrid ML ensemble - LSTM + LightGBM with FinBERT NLP sentiment analysis and technical indicators.',
        'Built automated ETL and feature engineering pipelines with model retraining workflows.',
        'Delivered end-to-end as a live web app at ysil.vercel.app with React framework and real-time data visualization.',
      ],
    },
    {
      title: 'CityFlow - Urban Mobility Analytics Platform',
      subtitle: 'Real-Time Data Simulation & KPI Dashboard',
      year: '2026',
      period: '2026',
      description: 'Built a real-time urban mobility analytics platform with simulated demand, congestion, and surge-pricing KPIs in live dashboards.',
      tags: ['Python', 'React', 'TypeScript', 'Recharts', 'Zustand', 'Three.js'],
      color: '#E8570C',
      featured: true,
      starred: true,
      category: 'dev',
      liveUrl: 'https://sim-city-alpha.vercel.app/',
      achievements: [
        'Designed a multi-variable simulation engine across fleet size, surge pricing, weather, time-of-day demand curves, and zone-level demand weighting to generate continuous KPI data streams.',
        'Built live Recharts dashboards with rolling time-series windows for average wait time, congestion index, fleet utilization, and revenue, updated at fixed intervals for trend analysis.',
        'Implemented zone-segmented demand modeling and dynamic surge pricing logic to simulate demand elasticity and revenue optimization trade-offs under changing conditions.',
        'Applied granular Zustand subscriptions and selective re-rendering to reduce analytics UI overhead and keep continuous data updates smooth across devices.',
        'Created an onboarding analytics guide documenting KPI causality, helping users understand how each simulation lever affects downstream metrics.',
      ],
    },
    {
      title: 'CodeGraph Intelligence',
      subtitle: 'AI-Native Repository Intelligence',
      year: '2026',
      period: '2026 - Present',
      description: 'A semantic code intelligence tool that builds a knowledge graph of your entire codebase, letting AI agents and developers search, query, and navigate code the way you think about it.',
      tags: ['Python', 'Graph DB', 'AI Agents', 'Semantic Search', 'LLM'],
      color: '#7C3AED',
      featured: true,
      starred: true,
      category: 'ml',
      githubUrl: 'https://github.com/kunal202426/CodeGraph-Intelligence',
      achievements: [
        'Building a semantic code intelligence platform that maps repository structure into queryable knowledge graphs.',
        'Serves as persistent memory layer for AI coding agents with vector-based semantic search and context retrieval.',
      ],
    },
    {
      title: 'System Design Simulator',
      subtitle: 'Distributed Systems & Chaos Engineering',
      year: '2026',
      period: '2026',
      description: 'A hands-on distributed systems simulator where you can model real failure scenarios, inject faults, and watch systems recover - backed by M/M/1 queueing theory.',
      tags: ['React', 'FastAPI', 'ReactFlow', 'WebSockets', 'Distributed Systems'],
      color: '#00E5FF',
      featured: true,
      starred: true,
      category: 'dev',
      liveUrl: 'https://system-design-simulator-weld.vercel.app/',
      githubUrl: 'https://github.com/kunal202426',
      achievements: [
        'Built a full-stack distributed systems simulator using React (ReactFlow), FastAPI, and WebSockets.',
        'Modeled failure scenarios via M/M/1 queueing theory, chaos engineering, and probabilistic fault injection (node crashes, latency spikes, traffic surges).',
        'Designed a live metrics dashboard for real-time observation of system state, throughput, and recovery patterns under varied fault conditions.',
      ],
    },
    {
      title: 'Self-Healing Neural Network Agent',
      subtitle: 'AI Reliability & Autonomous Recovery',
      year: '2026',
      period: '2026',
      description: 'A neural network that fixes itself when it starts degrading - the agent watches training in real time, spots what is going wrong, and applies the right recovery strategy without any manual tuning.',
      tags: ['Python', 'PyTorch', 'FastAPI', 'React', 'AI Agent', 'Neural Networks'],
      color: '#39FF14',
      featured: true,
      category: 'ml',
      githubUrl: 'https://github.com/kunal202426/Self-healing-neural-network-agent',
      achievements: [
        'Built an autonomous healing agent that monitors live training metrics and triggers targeted recovery actions (hyperparameter adjustment, layer injection, and weight reinitialization) when degradation is detected.',
        'Designed a multi-strategy recovery engine selecting the optimal healing strategy (learning rate tuning, batch norm injection, dropout regulation) based on anomaly type classification.',
        'Created a real-time React dashboard visualizing training health, anomaly detection events, and healing action history with live WebSocket-driven metric streaming.',
        'Implemented a FastAPI backend orchestrating the agent loop, metric ingestion, and strategy dispatch with full REST API exposure for external integration.',
      ],
    },
    {
      title: 'Real-Time Eye-Tracking Inference System',
      subtitle: 'Computer Vision & ML',
      year: '2026',
      period: '2026 - Present',
      description: 'Building a real-time gaze estimation system using computer vision and deep learning with Kalman smoothing and temporal voting ensemble.',
      tags: ['Python', 'Computer Vision', 'Deep Learning', 'Kalman Filtering', 'ML'],
      color: '#FF3CAC',
      featured: false,
      category: 'ml',
      githubUrl: 'https://github.com/kunal202426',
      achievements: [
        'Implemented Kalman smoothing, temporal voting ensemble, and calibration improvements for robust inference without model retraining.',
        'Conducting webcam domain adaptation research to bridge the gap between training data and real-world USB webcam deployment.',
      ],
    },
    {
      title: 'Autonomous Agent Marketplace',
      subtitle: 'AI Agents & Blockchain Escrow',
      year: '2025',
      period: '2025 - Present',
      description: 'A hybrid system combining AI agents with blockchain-based escrow to coordinate task execution and payments. Separates execution (off-chain) from trust and settlement (on-chain) for verifiable outcomes.',
      tags: ['Python', 'Solidity', 'AI Agents', 'Blockchain', 'Smart Contracts'],
      color: '#10B981',
      featured: false,
      category: 'blockchain',
      githubUrl: 'https://github.com/kunal202426/Autonomous-agent-marketplace',
      achievements: [
        'Built hybrid AI + blockchain system separating off-chain execution from on-chain trust and settlement.',
        'Implements blockchain-based escrow for verifiable, trustless payment coordination between autonomous agents.',
      ],
    },
    {
      title: 'JobHuntPro',
      subtitle: 'Job Automation & AI Outreach',
      year: '2025',
      period: '2025',
      description: 'A self-hosted job-hunting automation platform that combines LinkedIn job scraping with AI-powered cold email outreach. Multi-user SaaS with per-user credential isolation, an admin dashboard, and a Chrome extension for one-click LinkedIn scraping.',
      tags: ['Python', 'FastAPI', 'AI', 'Chrome Extension', 'SaaS', 'LinkedIn'],
      color: '#6C63FF',
      featured: false,
      category: 'dev',
      liveUrl: 'https://jobhuntpro-lemon.vercel.app/',
      githubUrl: 'https://github.com/kunal202426',
      achievements: [
        'Built LinkedIn job scraper with AI-powered cold email generator for automated outreach.',
        'Multi-user SaaS architecture with per-user credential isolation and admin dashboard.',
        'Developed a Chrome extension for one-click LinkedIn job scraping.',
      ],
    },
    {
      title: 'Fertilizer Subsidy Distribution Platform',
      subtitle: 'Blockchain / Web3 DApp',
      year: '2025',
      period: '2025',
      description: 'Ethereum-based DApp for tamper-proof subsidy allocation using smart contracts and Web3.js.',
      tags: ['Solidity', 'Ethereum', 'Web3.js', 'React', 'Smart Contracts', 'DApp'],
      color: '#9D97FF',
      featured: false,
      category: 'blockchain',
      githubUrl: 'https://github.com/kunal202426',
      achievements: [
        'Built a DApp for tamper-proof subsidy allocation using Ethereum smart contracts (Solidity) and Web3.js.',
        'Implemented React + MetaMask frontend with on-chain redemption logic and event-driven audit trails.',
      ],
    },
    {
      title: 'Official Website - Team Levitate Hyperloop',
      subtitle: '3D Web & Full Stack',
      year: '2024',
      period: '2024',
      description: '3D interactive, fully responsive website in Three.js and React with performance-optimized rendering.',
      tags: ['Three.js', 'React', 'WebGL', 'Responsive Design', 'DevOps', 'SEO'],
      color: '#00E5FF',
      featured: true,
      category: 'design',
      liveUrl: 'https://www.levitatehyperloop.com/',
      githubUrl: 'https://github.com/kunal202426',
      achievements: [
        'Designed and deployed a 3D interactive, fully responsive website in Three.js and React.',
        'Optimized rendering and performance for global accessibility with real-time hardware data integration.',
      ],
    },
  ],
  skills: {
    languages: ['Java', 'Python', 'JavaScript (ES6+)', 'Solidity', 'TypeScript'],
    frontend: [
      { name: 'React.js', level: 95 },
      { name: 'Three.js', level: 85 },
      { name: 'ReactFlow', level: 82 },
      { name: 'HTML5', level: 98 },
      { name: 'CSS3', level: 93 },
      { name: 'Responsive UI Design', level: 92 },
      { name: 'Framer Motion', level: 87 },
      { name: 'Tailwind CSS', level: 93 },
    ],
    backend: [
      { name: 'Node.js', level: 90 },
      { name: 'FastAPI', level: 88 },
      { name: 'Express.js', level: 85 },
      { name: 'RESTful APIs', level: 92 },
      { name: 'WebSocket', level: 80 },
      { name: 'Microservices', level: 82 },
      { name: 'System Design', level: 85 },
    ],
    databases: ['PostgreSQL', 'MongoDB', 'Firebase'],
    mlai: [
      { name: 'TensorFlow', level: 85 },
      { name: 'Scikit-learn', level: 88 },
      { name: 'LSTM', level: 80 },
      { name: 'LightGBM', level: 82 },
      { name: 'NLP (FinBERT)', level: 78 },
      { name: 'Deep Learning', level: 83 },
      { name: 'Computer Vision', level: 87 },
      { name: 'Kalman Filtering', level: 82 },
      { name: 'Feature Engineering', level: 86 },
      { name: 'ETL Pipelines', level: 84 },
      { name: 'Data Analysis', level: 89 },
      { name: 'Web Scraping', level: 85 },
    ],
    blockchain: ['Ethereum', 'Solidity', 'Smart Contracts', 'Web3.js', 'DApps', 'Hyperledger Fabric'],
    tools: [
      { name: 'Git', level: 95 },
      { name: 'GitHub', level: 93 },
      { name: 'AWS', level: 82 },
      { name: 'Vercel', level: 90 },
      { name: 'Figma', level: 85 },
      { name: 'Blender', level: 75 },
      { name: 'VS Code', level: 98 },
    ],
    concepts: ['Distributed Systems', 'Chaos Engineering', 'CI/CD', 'Agile/Scrum', 'SDLC', 'OOP'],
  },
  achievements: [
    {
      title: 'Winner - Global Hyperloop Competition',
      subtitle: "Asia's First Hyperloop Competition, IIT Madras",
      year: 2025,
      description: 'Secured six awards across engineering, design, and technical presentation - representing VIT Vellore.',
      url: 'https://www.ghciitm.com/',
    },
    {
      title: 'National Semi-Finalist - Flipkart GRiD 7.0',
      year: 2025,
      description: 'Advanced to national semi-finals in a highly competitive real-world software engineering challenge.',
      url: 'https://www.flipkartcareers.com/flipkart/grid',
    },
  ],
  certifications: [
    {
      title: 'Technology Software Development',
      issuer: 'Citi',
      year: 2026,
      description: 'Job simulation covering software engineering practices, system design, and technology infrastructure within a global banking environment.',
    },
    {
      title: 'McKinsey Forward Program',
      issuer: 'McKinsey & Company',
      year: 2026,
      description: 'Future-skills program covering problem-solving, digital fluency, communication, and leadership frameworks used by McKinsey consultants.',
    },
    {
      title: 'Data Analytics - Skill Up',
      issuer: 'GeeksforGeeks',
      year: 2026,
      description:
        '9-week program, 98% (874/895 modules) - Python, NumPy, Pandas, EDA, SQL, Power BI, Tableau, Excel, Web Scraping; capstone projects in end-to-end data analysis and web scraping integration.',
    },
    {
      title: 'Data Analytics Job Simulation',
      issuer: 'Deloitte Australia',
      year: 2025,
      description: 'Hands-on simulation covering data analysis, forensic technology, and business insights, modeled on real Deloitte client engagements.',
    },
    {
      title: 'Blockchain Developer Certification',
      issuer: 'IBM Career Education',
      year: 2025,
      description:
        'Blockchain fundamentals, smart contract development, Hyperledger Fabric, and DApp architecture.',
    },
    {
      title: 'Full Stack Web Development (MERN)',
      issuer: 'Apna College',
      year: 2024,
      description: 'Built and deployed multiple production full-stack web applications end-to-end.',
    },
  ],
}
